import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

// Register standard fonts
// Font.register({ family: 'Helvetica-Bold', src: ... });

const styles = StyleSheet.create({
  page: {
    padding: 50,
    backgroundColor: '#ffffff',
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 30,
    borderBottom: 2,
    borderBottomColor: '#4f46e5',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#111827',
    textTransform: 'uppercase',
  },
  subtitle: {
    fontSize: 10,
    color: '#6b7280',
    marginTop: 4,
    letterSpacing: 1,
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#4f46e5',
    marginBottom: 10,
    textTransform: 'uppercase',
    borderBottom: 1,
    borderBottomColor: '#e5e7eb',
    paddingBottom: 4,
  },
  row: {
    flexDirection: 'row',
    marginBottom: 6,
  },
  label: {
    width: 120,
    fontSize: 10,
    color: '#6b7280',
    fontWeight: 'bold',
  },
  value: {
    flex: 1,
    fontSize: 10,
    color: '#111827',
  },
  bodyText: {
    fontSize: 10,
    lineHeight: 1.5,
    color: '#374151',
    textAlign: 'justify',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 50,
    right: 50,
    borderTop: 1,
    borderTopColor: '#e5e7eb',
    paddingTop: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  footerText: {
    fontSize: 8,
    color: '#9ca3af',
  }
});

interface ContractProps {
  gigId: string;
  artistName: string;
  venueName: string;
  eventDate: string;
  payout: string;
  terms: string;
}

export const PerformanceContract = ({ 
  gigId, 
  artistName, 
  venueName, 
  eventDate, 
  payout, 
  terms 
}: ContractProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Performance Agreement</Text>
        <Text style={styles.subtitle}>Reference ID: {gigId}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>1. Parties involved</Text>
        <View style={styles.row}>
          <Text style={styles.label}>ARTIST:</Text>
          <Text style={styles.value}>{artistName}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>VENUE:</Text>
          <Text style={styles.value}>{venueName}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>2. Event Details</Text>
        <View style={styles.row}>
          <Text style={styles.label}>DATE:</Text>
          <Text style={styles.value}>{eventDate}</Text>
        </View>
        <View style={styles.row}>
          <Text style={styles.label}>TOTAL PAYOUT:</Text>
          <Text style={styles.value}>{payout}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>3. Agreed Terms & Clauses</Text>
        <Text style={styles.bodyText}>{terms}</Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>4. Platform Terms</Text>
        <Text style={styles.bodyText}>
          This agreement is facilitated by Findabandtoday (FABT). A 5% platform service fee has been calculated into the payout totals. 
          Both parties agree to the FABT Terms of Service and Payout Policy.
        </Text>
      </View>

      <View style={styles.footer}>
        <Text style={styles.footerText}>Generated by Findabandtoday AI Negotiator</Text>
        <Text style={styles.footerText}>Page 1 of 1</Text>
      </View>
    </Page>
  </Document>
);
