// src/lib/constants/tiers.ts

export const SUBSCRIPTION_TIERS = {
  ARTIST_BASIC: 'ARTIST_BASIC',
  ARTIST_BIZ: 'ARTIST_BIZ',
  VENUE_FREE: 'VENUE_FREE',
  VENUE_PRO: 'VENUE_PRO',
  VENUE_COMMAND: 'VENUE_COMMAND',
  MAXIMIZER: 'MAXIMIZER',
  TOUR_BOOKING: 'TOUR_BOOKING',
  BOOKING_FEE: 'BOOKING_FEE',
  AD_OPTION: 'AD_OPTION',
} as const;

export type SubscriptionTier = typeof SUBSCRIPTION_TIERS[keyof typeof SUBSCRIPTION_TIERS];

export const TIER_PRICE_IDS: Record<string, string> = {
  [SUBSCRIPTION_TIERS.ARTIST_BIZ]: 'price_1T86QdKQ7llXqRzhQDU7q2wo',
  [SUBSCRIPTION_TIERS.VENUE_PRO]: 'price_1T86QeKQ7llXqRzhmkQkDn3O',
  [SUBSCRIPTION_TIERS.VENUE_COMMAND]: 'placeholder_venue_command',
  [SUBSCRIPTION_TIERS.MAXIMIZER]: 'price_1T86QfKQ7llXqRzhu9jHOcLh',
  [SUBSCRIPTION_TIERS.TOUR_BOOKING]: 'price_1T86IDKQ7llXqRzhunih8wE9',
  [SUBSCRIPTION_TIERS.BOOKING_FEE]: 'price_1T86QfKQ7llXqRzhaSzZS8Mt',
  [SUBSCRIPTION_TIERS.AD_OPTION]: 'price_1T86QgKQ7llXqRzh0CV5TQvR',
};
