// src/lib/constants/tiers.ts

export const SUBSCRIPTION_TIERS = {
  ARTIST_BASIC: 'ARTIST_BASIC',
  ARTIST_BIZ: 'ARTIST_BIZ',
  VENUE_FREE: 'VENUE_FREE',
  VENUE_PRO: 'VENUE_PRO',
  VENUE_COMMAND: 'VENUE_COMMAND',
  MAXIMIZER: 'MAXIMIZER',
} as const;

export type SubscriptionTier = typeof SUBSCRIPTION_TIERS[keyof typeof SUBSCRIPTION_TIERS];

export const TIER_PRICE_IDS: Record<string, string> = {
  [SUBSCRIPTION_TIERS.ARTIST_BIZ]: process.env.NEXT_PUBLIC_STRIPE_ARTIST_BIZ_PRICE_ID!,
  [SUBSCRIPTION_TIERS.VENUE_PRO]: process.env.NEXT_PUBLIC_STRIPE_VENUE_PRO_PRICE_ID!,
  [SUBSCRIPTION_TIERS.VENUE_COMMAND]: process.env.NEXT_PUBLIC_STRIPE_VENUE_COMMAND_PRICE_ID!,
  [SUBSCRIPTION_TIERS.MAXIMIZER]: process.env.NEXT_PUBLIC_STRIPE_MAXIMIZER_PRICE_ID!,
};
