// src/lib/constants/tiers.ts

export const SUBSCRIPTION_TIERS = {
  ARTIST_BASIC: 'ARTIST_BASIC',
  ARTIST_BIZ: 'ARTIST_BIZ',
  VENUE_FREE: 'VENUE_FREE',
  VENUE_PRO: 'VENUE_PRO',
  VENUE_COMMAND: 'VENUE_COMMAND',
  MAXIMIZER: 'MAXIMIZER',
  TOUR_BOOKING: 'TOUR_BOOKING',
  BOOKING_FEE: 'BOOKING_FEE',
  AD_OPTION: 'AD_OPTION',
} as const;

export type SubscriptionTier = typeof SUBSCRIPTION_TIERS[keyof typeof SUBSCRIPTION_TIERS];

export const TIER_PRICE_IDS: Record<string, string> = {
  [SUBSCRIPTION_TIERS.ARTIST_BIZ]: process.env.NEXT_PUBLIC_STRIPE_BAND_BIZ_PRICE_ID || '',
  [SUBSCRIPTION_TIERS.VENUE_PRO]: process.env.NEXT_PUBLIC_STRIPE_VENUE_PRO_PRICE_ID || '',
  [SUBSCRIPTION_TIERS.VENUE_COMMAND]: process.env.NEXT_PUBLIC_STRIPE_AD_OPTION_PRICE_ID || '',
  [SUBSCRIPTION_TIERS.MAXIMIZER]: process.env.NEXT_PUBLIC_STRIPE_MAXIMIZER_PRICE_ID || '',
  [SUBSCRIPTION_TIERS.TOUR_BOOKING]: process.env.NEXT_PUBLIC_STRIPE_TOUR_BOOKING_PRICE_ID || '',
  [SUBSCRIPTION_TIERS.BOOKING_FEE]: process.env.NEXT_PUBLIC_STRIPE_BOOKING_FEE_PRICE_ID || '',
  [SUBSCRIPTION_TIERS.AD_OPTION]: process.env.NEXT_PUBLIC_STRIPE_AD_OPTION_PRICE_ID || '',
};
